### ISSUE TITLE
HiddenField with InputRequired validator produces invalid HTML

### ISSUE THREAD

**Issue by dalepotter** [pallets-eco/wtforms#682]
### Actual Behavior

```python
>>> import wtforms
>>> class F(wtforms.Form):
...     foo = wtforms.HiddenField(default='bar', validators=[wtforms.validators.AnyOf(['bar']), wtforms.validators.InputRequired()])
... 
>>> f = F()
>>> f.foo()
Markup('<input id="foo" name="foo" required type="hidden" value="bar">')
```

A minimal HTML page featuring this field would look like this.

```
<!DOCTYPE html>
  <head>
    <title>Example page</title>
  </head>
  <input id="foo" name="foo" required type="hidden" value="bar">
</html>
```

This HTML yields two validation errors (tested using the [W3 HTML validator](https://validator.w3.org/nu/#textarea)):
- Error: Attribute required not allowed on element input at this point.
- Error: Attribute required is only allowed when the input type is checkbox, date, datetime-local, email, file, month, number, password, radio, search, tel, text, time, url, or week.

### Expected Behavior

```python
>>> import wtforms
>>> class F(wtforms.Form):
...     foo = wtforms.HiddenField(default='bar', validators=[wtforms.validators.AnyOf(['bar']), wtforms.validators.InputRequired()])
... 
>>> f = F()
>>> f.foo()
Markup('<input id="foo" name="foo" type="hidden" value="bar">')
```

### Environment

* Python version: 3.6.9
* wtforms version: 2.3.3

**Comment by azmeuk** [comment]
The [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attributes) does agree:

> required is a Boolean attribute which, if present, indicates that the user must specify a value for the input before the owning form can be submitted. The required attribute is supported by text, search, url, tel, email, date, month, week, time, datetime-local, number, password, checkbox, radio, and file inputs.

**Comment by davidism** [comment]
Unless there's a straightforward fix for this, I'm not particularly concerned with satisfying this validation error, especially since it doesn't cause any issues.

**Comment by azmeuk** [comment]
@dalepotter what exactly is your usecase?
