### ISSUE TITLE
Pyright does not infer types for wtforms

### ISSUE THREAD

**Issue by ilkiri23** [pallets-eco/wtforms#848]
I'm trying to create a FolderForm instance, but pyright infers the type as Any
Also tried to install types-WTForms to solve the problem, but it didn't work for me

### Actual Behavior
```python
from wtforms import Form, StringField

class FolderForm(Form):
    name = StringField('Name')
 
form = FolderForm() # form is Any
```
<img width="180" alt="Screenshot 2024-06-20 at 22 53 10" src="https://github.com/wtforms/wtforms/assets/96888709/3ba99afc-aa3a-43a4-ae46-ba9f95b4cb42">

### Expected Behavior

`form` has the `FolderForm` type

### Environment

* Python version: 3.12.4
* WTForms version: 3.1.2
* types-WTForms version: 3.1.0.20240425

**Comment by ultinvincible** [comment]
I'm having the same problem with the VSCode extension Pylance, which uses Pyright.
Versions 24.4.101 pre-release and earlier do not have this problem.
Versions 24.4.102 pre-release, which updates Pyright from 1.1.358 to 1.1.359, and later have this problem.

- Python version: 3.12.4
- WTForms==3.1.2
- types-WTForms==3.1.0.20240425

**Comment by Daverball** [comment]
Issues with type stubs should be reported in https://github.com/python/typeshed where these stubs are hosted.

I've implemented a fix in [this PR](https://github.com/python/typeshed/pull/12875) so this should be fixed in a future release of `types-WTForms`
