### ISSUE TITLE
Adding entries to FieldList

### ISSUE THREAD

**Issue by Lopkop** [pallets-eco/wtforms#850]
### Actual Behavior

This is my fields and html code:
```python
class FileForm(FlaskForm):
    filename = StringField('Filename')
    value = TextAreaField('Paste', validators=[DataRequired()])


class PasteForm(FlaskForm):
    paste = FieldList(FormField(FileForm), min_entries=1)
    submit = SubmitField('Create paste')
```

```html
{% for field in form.paste %}
<p>
    {{ field.filename(placeholder='Filename') }}

</p>
<p>
    {{ field.value(wrap='off') }}
</p>
{% endfor %}
<form>
```

I found on reddit, that format is <form_variable_name>-<id_number> for creating new entries. So I added it, but I just got new blank form in FieldList.
**First question**: Why there is no information about this in documentation?
**Second question**: Why below html just adds blank form to FieldList with blank ```filename``` and ```value``` ? (see result below)
```html 
<input name="paste-1" type="text">
<textarea name="paste-1"></textarea>
```

This is an output if I am filling all 2 forms:
```[{'filename': 'test.py', 'value': "print()", 'csrf_token': None}, {'filename': None, 'value': None, 'csrf_token': None}]```
As you can see only first form has values

### What I expected to see?
1) Documentation about this feature
2) ```filename``` and ```value``` filled with values

### Environment

* Python version: 3.11.9
* wtforms version: 3.1.2

**Comment by Daverball** [comment]
Since you're using a `FormField` there is an additional prefix for each subfield, so it's `paste-filename-1` and `paste-value-1` respectively for adding a second field to the list dynamically. If you already have `n` entries the `1` needs to be a `n` instead.
