### ISSUE TITLE
Validator order isn't immediately apparent

### ISSUE THREAD

**Issue by miketheman** [pallets-eco/wtforms#852]
I was trying to understand why validators placed on the field wouldn't be validated prior to in-line validators, and came up with this (albeit impossible) scenario to demonstrate the problem.

### Actual Behavior

In this example, the StringField validator isn't being called at all, as shown in `f.errors`:

```python
>>> from webob.multidict import MultiDict
>>> from wtforms import Form, StringField
>>> from wtforms.validators import ValidationError, Length
>>>
>>> class F(Form):
...     name = StringField(validators=[Length(min=50)])
...     def validate_name(form, field):
...         if len(field.data) > 50:
...             raise ValidationError("Name must be less than 50 characters")
...
>>> f = F(MultiDict([("name", "a" * 51)]))
>>>
>>> assert not f.validate()
>>> assert f.errors == {"name": ["Name must be less than 50 characters"]}
```

### Expected Behavior

In this example, I flip the input condition to a shorter string, and expect that the `Length` validator tell me that it's not long enough before calling `validate_name()`.

```python
>>> from webob.multidict import MultiDict
>>> from wtforms import Form, StringField
>>> from wtforms.validators import ValidationError, Length
>>>
>>> class F(Form):
...     name = StringField(validators=[Length(min=50)])
...     def validate_name(form, field):
...         if len(field.data) > 50:
...             raise ValidationError("Name must be less than 50 characters")
...
>>> f = F(MultiDict([("name", "a")]))
>>>
>>> assert not f.validate()
>>> assert f.errors == {"name": ["Field must be at least 50 characters long."]}
```

In my head, the field validation should happen before a form's in-line field validation, but had trouble finding the order expressed in the documentation.

### Environment

* Python version: 3.12.4
* wtforms version: 3.1.2

**Comment by Daverball** [comment]
I don't fully understand your expected vs. actual behavior. They both look correct to me and it's what happens, your two conditions are reciprocal, so they can't both trigger an error at the same time.

Field validators definitely run before in-line validators, since they get picked up as extra validators:
https://github.com/pallets-eco/wtforms/blob/f9a999e5b7406db05d9e0e02dd85ab25253d40a6/src/wtforms/form.py#L320-L330

And extra validators get executed last:
https://github.com/pallets-eco/wtforms/blob/f9a999e5b7406db05d9e0e02dd85ab25253d40a6/src/wtforms/fields/core.py#L233-L234

However `ValidationError` does not stop the validation chain. If you wanted to prevent `validate_name` from running you would need to create a custom length validator that emits a `StopValidation` (with a message it will be picked up as an error like `ValidationError`, but a plain `StopValidation` will force the validation chain to succeed, this is used in `Optional` to prevent further validators from running).

Alternatively you can check for errors in your in-line validator if you don't want it to run if there's already another error:

```python
if self.errors:
    return
```

**Comment by miketheman** [comment]
Kinda wish this wasn't summarily closed based on a single response inquiring about the observed behavior, and asking for clarity.
Ultimately, the issue stems from a lack of clarity in the documentation, which is still an issue.

Thanks @Daverball for the in-depth response, and I guess that points out a weakness in my reproduction scenario here, apologies, I thought it was sufficient to make the point, but it wasn't.

In [my real world example](https://github.com/pypi/warehouse/blob/4eb7661f5e2ca0b6c52e8b62dc4fa5e972477b4a/warehouse/accounts/forms.py#L79-L95), I do indeed have a custom validator that [implements a StopValidation](https://github.com/pypi/warehouse/blob/4eb7661f5e2ca0b6c52e8b62dc4fa5e972477b4a/warehouse/accounts/forms.py#L62-L76) when it's hit, and that's how I originally ended up here.

In this code, I'd expect that the `username` is checked against             `wtforms.validators.InputRequired()`, then my custom `PreventNullBytesValidator`, and only after passing that, move along to the `validate_username()` step, as you described with the `extra_validators` code.

However, we observed that this was not happening, evidenced by usernames with null bytes being passed into the `user_service.find_userid()` function, which ended up failing since the downstream service disallows null bytes - not caught by the validator.

I ended up resolving this by extracting the inline validator to a module-level function, and that works, but it wasn't clear why this would happen, considering the logic you linked to.

**Comment by miketheman** [comment]
Kinda wish this wasn't summarily closed based on a single response inquiring about the observed behavior, and asking for clarity.
Ultimately, the issue stems from a lack of clarity in the documentation, which is still an issue.

Thanks @Daverball for the in-depth response, and I guess that points out a weakness in my reproduction scenario here, apologies, I thought it was sufficient to make the point, but it wasn't.

In [my real world example](https://github.com/pypi/warehouse/blob/4eb7661f5e2ca0b6c52e8b62dc4fa5e972477b4a/warehouse/accounts/forms.py#L79-L95), I do indeed have a custom validator that [implements a StopValidation](https://github.com/pypi/warehouse/blob/4eb7661f5e2ca0b6c52e8b62dc4fa5e972477b4a/warehouse/accounts/forms.py#L62-L76) when it's hit, and that's how I originally ended up here.

In this code, I'd expect that the `username` is checked against             `wtforms.validators.InputRequired()`, then my custom `PreventNullBytesValidator`, and only after passing that, move along to the `validate_username()` step, as you described with the `extra_validators` code.

However, we observed that this was not happening, evidenced by usernames with null bytes being passed into the `user_service.find_userid()` function, which ended up failing since the downstream service disallows null bytes - not caught by the validator.

I ended up resolving this by extracting the inline validator to a module-level function, and that works, but it wasn't clear why this would happen, considering the logic you linked to.

**Comment by Daverball** [comment]
The only way I can think of this scenario happening is if a class that uses this mixin, either directly or through one of its parent classes, defines its own `username` field but without the `PreventNullBytesValidator`, since `validate_username` will be inherited even if the field is replaced.

**Comment by Daverball** [comment]
@miketheman I think I found your bug, you're clearing `username.validators`, which doesn't get rid of the `validate_name` method. A better way to do this might be to insert a dummy validator at the start that just does `raise StopValidation()`

https://github.com/pypi/warehouse/blob/d1c002e8b5c1233f505721cf83c877cb3117092e/warehouse/manage/forms.py#L117

**Comment by miketheman** [comment]
> you're clearing `username.validators`, which doesn't get rid of the `validate_name` method...

That's an interesting path to follow - but wouldn't that only apply to usage of `CreateInternalRoleForm` ? We've seen the null bytes in username not be caught in [`LoginForm`](https://github.com/pypi/warehouse/blob/e7762bb591fc399f8a88798d5f8ac033267fb7ce/warehouse/accounts/forms.py#L442) (the only one that uses this instance of `UsernameMixin`, we have another in a different module...)  - which led me to [this refactor](https://github.com/pypi/warehouse/pull/16599) - and we haven't seen it occur since.

So I'm still a bit confused how this happens.

**Comment by Daverball** [comment]
Good question, that just was the lowest hanging fruit that turned up by searching for `username.validators` in the repository. I can't really see a way for this case to happen under normal circumstances, since WTForms doesn't do anything overly clever to build and execute the validation chain. So as long as the validation chain is correct, it should not matter whether it's supplied as an argument or as a method. It would only really matter once you start to manipulate the validators stored on the field.

**Comment by miketheman** [comment]
> It would only really matter once you start to manipulate the validators stored on the field.

That seems more likely. I suspect we're doing something weird. I discovered we're subclassing all of `Form` since we predated `form_errors` and wrote our own, so it's possible something is happening there.

I'll close this for now and keep digging. Thanks for the help!
